version: "3"
services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    # env_file:
    #   - .env
    volumes:
      - "/app/node_modules"
      - "./server:/app"
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - "/app/node_modules"
      - "./client:/app"
    stdin_open: true
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    depends_on:
      - client
    ports:
      - "8080:80"